const prices={'Сайт-визитка':'от 50 000 ₽','Лендинг':'от 80 000 ₽','Сайт для бизнеса':'от 150 000 ₽','Интернет-магазин':'от 250 000 ₽','Нестандартный проект':'После обсуждения'};
const form=document.querySelector('#brief-form');
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_project_brief',title:'Выбрать тип сайта',description:'Выбирает услугу в брифе и показывает стартовую цену. Не отправляет заявку и не скачивает файл.',inputSchema:{type:'object',properties:{service:{type:'string',enum:Object.keys(prices)}},required:['service'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Object.hasOwn(prices,input.service))throw new Error('Неизвестная услуга');for(const radio of form.elements.service)radio.checked=radio.value===input.service;updateEstimate();return {service:input.service,estimate:document.querySelector('#estimate').textContent,sent:false}}})).catch(()=>{});}catch{}}
function updateEstimate(){document.querySelector('#estimate').textContent=prices[new FormData(form).get('service')];document.querySelector('#status').textContent=''}
form.addEventListener('change',updateEstimate);
document.querySelectorAll('[data-service]').forEach(link=>link.addEventListener('click',()=>{for(const input of form.elements.service)input.checked=input.value===link.dataset.service;updateEstimate()}));
form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);const name=data.get('name').trim(),description=data.get('description').trim();if(!name||description.length<10){document.querySelector('#status').textContent='Укажите имя и опишите проект хотя бы в 10 символах.';return}const content=['AEVUM / Бриф на разработку сайта','',`Имя / компания: ${name}`,`Тип сайта: ${data.get('service')}`,`Стартовый ориентир: ${prices[data.get('service')]}`,'','О проекте:',description,'','Стоимость и сроки уточняются после обсуждения.','Этот бриф сохранён на устройстве и не отправлен разработчику.'].join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+content],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='aevum-brief.txt';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#status').textContent='Бриф подготовлен к скачиванию. Заявка не отправлялась.'});
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reducedMotion){
 const targets=document.querySelectorAll('.approach-content,.principles>div,.services-heading,.service-list details,.story-copy,.steps article,.brief-grid>div');
 if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});targets.forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--delay',`${(i%3)*75}ms`);observer.observe(el)})}
 if(window.matchMedia('(pointer: fine)').matches){const hero=document.querySelector('.hero');hero.addEventListener('pointermove',event=>{const b=hero.getBoundingClientRect();hero.style.setProperty('--mx',`${((event.clientX-b.left)/b.width-.5)*12}px`);hero.style.setProperty('--my',`${((event.clientY-b.top)/b.height-.5)*12}px`)});hero.addEventListener('pointerleave',()=>{hero.style.setProperty('--mx','0px');hero.style.setProperty('--my','0px')})}
}
