const prices={'Сайт-визитка':'от 50 000 ₽','Лендинг':'от 80 000 ₽','Сайт для бизнеса':'от 150 000 ₽','Интернет-магазин':'от 250 000 ₽','Нестандартный проект':'После обсуждения'};
const form=document.querySelector('#brief-form');
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_project_brief',title:'Выбрать тип сайта',description:'Выбирает услугу в брифе и показывает стартовую цену. Не отправляет заявку и не скачивает файл.',inputSchema:{type:'object',properties:{service:{type:'string',enum:Object.keys(prices)}},required:['service'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Object.hasOwn(prices,input.service))throw new Error('Неизвестная услуга');for(const radio of form.elements.service)radio.checked=radio.value===input.service;updateEstimate();return {service:input.service,estimate:document.querySelector('#estimate').textContent,sent:false}}})).catch(()=>{});}catch{}}
function updateEstimate(){document.querySelector('#estimate').textContent=prices[new FormData(form).get('service')];document.querySelector('#status').textContent=''}
form.addEventListener('change',updateEstimate);
document.querySelectorAll('[data-service]').forEach(link=>link.addEventListener('click',()=>{for(const input of form.elements.service)input.checked=input.value===link.dataset.service;updateEstimate()}));
form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);const name=data.get('name').trim(),description=data.get('description').trim();if(!name||description.length<10){document.querySelector('#status').textContent='Укажите имя и опишите проект хотя бы в 10 символах.';return}const content=['KODELIX / Бриф на разработку сайта','',`Имя / компания: ${name}`,`Тип сайта: ${data.get('service')}`,`Стартовый ориентир: ${prices[data.get('service')]}`,'','О проекте:',description,'','Стоимость и сроки уточняются после обсуждения.','Этот бриф сохранён на устройстве и не отправлен разработчику.'].join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+content],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='kodelix-brief.txt';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#status').textContent='Бриф подготовлен к скачиванию. Заявка не отправлялась.'});
// Motion is decorative: all content and actions remain usable without it.
const motionPreference=window.matchMedia('(prefers-reduced-motion: reduce)');
const finePointer=window.matchMedia('(pointer: fine)').matches;
let motionEnabled=!motionPreference.matches;
const root=document.documentElement;
const hero=document.querySelector('.hero');
const progress=document.createElement('div');progress.className='reading-progress';progress.setAttribute('aria-hidden','true');document.body.append(progress);
const motionButton=document.createElement('button');motionButton.type='button';motionButton.className='motion-toggle';document.querySelector('.hero-bottom').append(motionButton);
function setMotion(enabled){motionEnabled=enabled;root.classList.toggle('motion-paused',!enabled);motionButton.textContent=enabled?'Ⅱ  Анимация':'▷  Анимация';motionButton.setAttribute('aria-pressed',String(enabled));motionButton.setAttribute('aria-label',enabled?'Остановить анимацию':'Включить анимацию');if(!enabled){document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));root.style.setProperty('--scroll-drift','0px');hero.style.setProperty('--mx','0px');hero.style.setProperty('--my','0px');document.querySelectorAll('.magnetic').forEach(el=>el.style.translate='0px 0px')}if(enabled&&heroInView&&!document.hidden)startParticles()}
motionPreference.addEventListener('change',event=>setMotion(!event.matches));
motionButton.addEventListener('click',()=>setMotion(!motionEnabled));
const title=document.querySelector('h1');
if(motionEnabled){const titleHTML=title.innerHTML;title.setAttribute('aria-label',titleHTML.replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,''));title.innerHTML=titleHTML.split(/<br\s*\/?\s*>/i).map((line,i)=>`<span class="title-line" aria-hidden="true"><span class="title-line-inner" style="--line-delay:${i*130}ms">${line}</span></span>`).join('')}
if(motionEnabled&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.approach-content,.principles>div,.services-heading,.service-list details,.steps article,.brief-grid>div').forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--delay',`${(i%3)*85}ms`);observer.observe(el)})}
if(finePointer){hero.addEventListener('pointermove',event=>{if(!motionEnabled)return;const b=hero.getBoundingClientRect();hero.style.setProperty('--mx',`${((event.clientX-b.left)/b.width-.5)*35}px`);hero.style.setProperty('--my',`${((event.clientY-b.top)/b.height-.5)*25}px`);hero.style.setProperty('--light-x',`${event.clientX-b.left}px`);hero.style.setProperty('--light-y',`${event.clientY-b.top}px`)});hero.addEventListener('pointerleave',()=>{hero.style.setProperty('--mx','0px');hero.style.setProperty('--my','0px')});document.querySelectorAll('.button-primary,.nav-cta,.submit').forEach(button=>{button.classList.add('magnetic');button.addEventListener('pointermove',event=>{if(!motionEnabled)return;const b=button.getBoundingClientRect();button.style.translate=`${(event.clientX-b.left-b.width/2)*.13}px ${(event.clientY-b.top-b.height/2)*.2}px`});button.addEventListener('pointerleave',()=>button.style.translate='0px 0px')});document.querySelectorAll('.service-list details').forEach(card=>{card.addEventListener('pointermove',event=>{if(!motionEnabled)return;const b=card.getBoundingClientRect();card.style.setProperty('--spot-x',`${event.clientX-b.left}px`);card.style.setProperty('--spot-y',`${event.clientY-b.top}px`)})})}
let scrollQueued=false;
function updateScroll(){const max=root.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?scrollY/max:0})`;if(motionEnabled){const b=hero.getBoundingClientRect();root.style.setProperty('--scroll-drift',`${Math.min(85,Math.max(0,-b.top*.12))}px`)}scrollQueued=false}
window.addEventListener('scroll',()=>{if(!scrollQueued){scrollQueued=true;requestAnimationFrame(updateScroll)}},{passive:true});window.addEventListener('resize',updateScroll);updateScroll();
// A lightweight constellation reacts to pointer position, and sleeps offscreen.
const canvas=document.createElement('canvas');canvas.className='hero-network';canvas.setAttribute('aria-hidden','true');hero.prepend(canvas);
const ctx=canvas.getContext('2d');let width=0,height=0,heroInView=true,particleFrame=0,lastTime=0;
const particles=Array.from({length:32},()=>({x:Math.random(),y:Math.random(),vx:(Math.random()-.5)*.009,vy:(Math.random()-.5)*.009}));
function sizeCanvas(){width=hero.clientWidth;height=hero.clientHeight;const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);if(ctx)ctx.setTransform(dpr,0,0,dpr,0,0)}
function drawParticles(time){particleFrame=0;if(!ctx||!motionEnabled||!heroInView||document.hidden)return;const dt=Math.min((time-lastTime)/1000,.05);lastTime=time;ctx.clearRect(0,0,width,height);for(const p of particles){p.x=(p.x+p.vx*dt+1)%1;p.y=(p.y+p.vy*dt+1)%1;ctx.beginPath();ctx.arc(p.x*width,p.y*height,1.3,0,Math.PI*2);ctx.fillStyle='rgba(130,152,255,.55)';ctx.fill()}for(let i=0;i<particles.length;i++){for(let j=i+1;j<particles.length;j++){const a=particles[i],b=particles[j],distance=Math.hypot((a.x-b.x)*width,(a.y-b.y)*height);if(distance<125){ctx.beginPath();ctx.moveTo(a.x*width,a.y*height);ctx.lineTo(b.x*width,b.y*height);ctx.strokeStyle=`rgba(97,123,255,${(1-distance/125)*.17})`;ctx.stroke()}}}particleFrame=requestAnimationFrame(drawParticles)}
function startParticles(){if(!particleFrame&&ctx){lastTime=performance.now();particleFrame=requestAnimationFrame(drawParticles)}}
sizeCanvas();window.addEventListener('resize',sizeCanvas);
if('IntersectionObserver' in window)new IntersectionObserver(entries=>{heroInView=entries[0].isIntersecting;if(heroInView&&motionEnabled)startParticles()}).observe(hero);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&heroInView&&motionEnabled)startParticles()});setMotion(motionEnabled);

document.querySelector("#crm-reload").addEventListener("click",()=>window.location.reload());
